/* ANGEL v2 - Admin Module | Protected */
var _ca=null,_ar=[],_rt=null;
window.addEventListener('DOMContentLoaded',()=>{var s=localStorage.getItem('angel_admin_session');if(s){try{_ca=JSON.parse(s);_sap();}catch(e){localStorage.removeItem('angel_admin_admin_session');}}});
async function _dl(ev){ev.preventDefault();var u=document.getElementById('loginUser').value.trim(),p=document.getElementById('loginPass').value,e=document.getElementById('loginError');if(!u||!p){e.textContent='\u8bf7\u8f93\u5165\u7528\u5bc6\u7801';e.style.display='block';return;}try{var sb=await _gS();var{data:ad,err}=await sb.from('admins').select('*').eq('username',u).maybeSingle();if(err||!ad){e.textContent='\u7528\u540d\u6216\u6216\u9519\u8bef';e.style.display='block';return;}_ca=ad;localStorage.setItem('angel_admin_session',JSON.stringify(ad));e.style.display='none';_sap();_t(`\u6b22\u8fce\u56de\uff0c${ad.username}`,'success')}catch(err){e.textContent=`\u767b\u5f55\u5931\u5931:${err.message}`;e.style.display='block';}}
function _lo(){_ca=null;localStorage.removeItem('angel_admin_session');document.getElementById('loginPanel').style.display='';document.getElementById('adminPanel').style.display='';_t('\u9000\u51fa\u51fa','info')}
async function _sap(){document.getElementById('loginPanel').style.display='none';document.getElementById('adminPanel').style.display='';document.getElementById('adminInfo').textContent=`\ud83d ${_ca.username}`;await _lSts();await _lPr()}
function _sat(t){document.querySelectorAll('#adminPanel .tab-btn').forEach(function(b){b.classList.remove('active')});document.querySelectorAll('#adminPanel .tab-panel').forEach(function(p){p.classList.remove('active')});var btns=document.querySelectorAll('#adminPanel .tab-btn');for(var i=0;i<btns.length;i++){if(btns[i].getAttribute('onclick')&&btns[i].getAttribute('onclick').indexOf("'"+t+"'")!==-1){btns[i].classList.add('active');break;}}document.getElementById('panel-'+t).classList.add('active');if(t==='pending')_lPr();if(t==='all')_lAR();}
async function _lSts(){try{var sb=await _gS();const[pend,appr,rej]=await Promise.all([sb.from('auth_requests').select('id',{count:'exact',head:true}).eq('status','pending'),sb.from('auth_requests').select('id',{count:'exact',head:true}).eq('status','approved'),sb.from('auth_requests').select('id',{count:'exact',head:true}).eq('status','rejected')]);var td=new Date().toISOString().split('T')[0];const{count:tC}=await sb.from('auth_requests').select('id',{count:'exact',head:true}).gte('created_at',td);document.getElementById('statPending').textContent=pend.count??0;document.getElementById('statApproved').textContent=appr.count??0;document.getElementById('statRejected').textContent=rej.count??0;document.getElementById('statToday').textContent=tC??0;document.getElementById('countPending').textContent=pend.count??0;}catch(e){console.error(e)}}
async function _lPr(){var c=document.getElementById('pendingList'),e=document.getElementById('pendingEmpty');c.innerHTML='<div class="loading"><div class="spinner"></div>\u52a0\u8f7d...</div>';try{var sb=await _gS();var{data,err}=await sb.from('auth_requests').select('*').eq('status','pending').order('created_at',{ascending:false});if(err)throw err;if(!data||!data.length){c.innerHTML='';e.style.display='';return;}e.style.display='none';c.innerHTML=data.map(_ri).join('');}catch(e){c.innerHTML=`<p style="color:var(--danger);text-align:center;padding:20px;">\u52a0\u8d25\u5931:${e.message}</p>`;}}
async function _lAR(){var c=document.getElementById('allList'),e=document.getElementById('allEmpty');c.innerHTML='<div class="loading"><div class="spinner"></div>\u52a0\u8f7d...</div>';try{var sb=await _gS();var{data,err}=await sb.from('auth_requests').select('*').order('created_at',{ascending:false}).limit(100);if(err)throw err;_ar=data||[];if(!_ar.length){c.innerHTML='';e.style.display='';return;}e.style.display='none';_rF(_ar);}catch(e){c.innerHTML=`<p style="color:var(--danger);text-align:center;padding:20px;">\u52a0\u8d25:${e.message}</p>`};}
function _fA(){var k=document.getElementById('searchInput').value.toLowerCase(),s=document.getElementById('filterStatus').value;var f=_ar;if(k)f=f.filter(r=>r.card_key.toLowerCase().includes(k)||r.user_auth_id.toLowerCase().includes(k));if(s)f=f.filter(r=>r.status===s);_rF(f)}
function _rF(list){var c=document.getElementById('allList'),e=document.getElementById('allEmpty');if(!list.length){c.innerHTML='';e.style.display='';return;}e.style.display='none';c.innerHTML=list.map(_ri).join('')}
function _ri(r){var a='';if(r.status==='pending')a=`<div class="request-actions"><button class="btn btn-success btn-sm" onclick="_ap('${r.id}','${r.user_auth_id}')">\u2705 \u540c\u610f</button><button class="btn btn-danger btn-sm" onclick="_sr('${r.id}')">\u274c \u62d2</button></div>`;return`<div class="request-item"><div class="request-meta"><span>${_sb(r.status)}</span><span class="request-time">${_ft(r.created_at)} (${_ta(r.created_at)})</span></div><div style="display:grid;grid-template-columns:auto 1fr;gap:4px;font-size:13px;"><span style="color:var(--text-muted);">卡密:</span><span style="word-break:break-all;">${r.card_key}</span><span style="color:var(--text-muted);">授权ID:</span><span style="word-break:break-all;font-size:12px;color:var(--text-secondary);">${r.user_auth_id}</span></div>${r.screenshot_url?`<img src="${r.screenshot_url}"class="screenshot-preview"style="margin-top:8px;"onclick="_lb('${r.screenshot_url}')"alt="\u622a\u622a">`:''}${r.license_token?`<div style="margin-top:10px;"><label style="font-size:11px;color:var(--success);">\u6388\u6743\u4ee4</label><div class="token-box"style="font-size:11px;padding:10px;">${r.license_token}</div></div>`:''}${r.reject_reason?`<div style="margin-top:8px;padding:8px;background:rgba(255,107,107,.04);border-radius:6px;font-size:12px;">\u62d2\u56e0\u539f\u56e0:${r.reject_reason}</div>`:''}${a}</div>`}
async function _ap(id,uid){if(!confirm('\u786e\u8ba4\u540c\uff1f\u7cfb\u81ea\u52a8\u751f\u4ee4?'))return;var sec=document.getElementById('settingSecret')?.value||_ca?.creator_secret;if(!sec){_t('\u5728\u8bbe\u7f16\u5b9a\u5bc6\u5219\u5bc6','error');_sat('settings');return;}try{var tk=_gt(sec,uid);if(!tk)throw new Error('\u4ee4\u7241\u751f\u6210\u5931\u5931');var sb=await _gS();var{err}=await sb.from('auth_requests').update({status:'approved',license_token:tk,reviewed_at:new Date().toISOString(),reviewer_id:_ca.id,updated_at:new Date().toISOString()}).eq('id',id);if(err) throw err;await sb.from('audit_logs').insert({action:'approved',target_id:id,admin_id:_ca.id,details:{tp:tk.substring(0,20)+'...'}});_t('\u2705 \u5df2\u901a\uff01\u4ee4\u4ee4\u751f\u6210\u751f!','success');await _lPr();await _lSts()}catch(err){console.error(err);_t(`\u5ba1\u8ba1\u5931\u5931:${err.message}`,'error')}}
function _sr(id){_rt=id;document.getElementById('rejectReason').value='';document.getElementById('rejectModal').classList.add('show')}
function _cr(){document.getElementById('rejectModal').classList.remove('show');_rt=null}
document.getElementById('confirmRejectBtn')?.addEventListener('click',async()=>{if(!_rt)return;var r=document.getElementById('rejectReason').value.trim();if(!r){_t('\u586b\u586b\u586b\u62d2\u539f\u56e0','error');return;}try{var sb=await _gS();var{err}=await sb.from('auth_requests').update({status:'rejected',reject_reason:r,reviewed_at:new Date().toISOString(),reviewer_id:_ca.id,updated_at:new Date().toISOString()}).eq('id',_rt);if(err) throw err;await sb.from('audit_logs').insert({action:'rejected',target_id:_rt,admin_id:_ca.id,details:{reason:r}});_cr();_t('\u5df2\u7edd','info');await _lPr();await _lSts()}catch(e){_t(`\u5931\u8d25:${e.message}`,'error')}});
async function _gt(sec,uid){try{var sb=await _gS();var{data,err}=await sb.rpc('generate_license_token',{p_creator_secret:sec,p_user_auth_id:uid});if(err)console.warn('RPC:',err);return data?.token||data||await _cd(sec,uid)}catch(e){return await _cd(sec,uid)}}
async function _cd(sec,uid){try{var r=await fetch('https://angelapiproxy.1354137307.workers.dev/proxy/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creator_key:sec,auth_id:uid})});var j=await r.json();return j.token||j.data?.token||j}catch(e){throw new Error('\u65e0\u6cd5\u8fde\u63a5\u63a5\u6388\u670a\u670d:'+e.message)}}
function _ss(){var s=document.getElementById('settingSecret').value.trim();if(!s){_t('\u586b\u586b\u5bc6\u5bc6','error');return;}localStorage.setItem('angel_creator_secret',s);_t('\u8bbe\u5b58\u5b58','success')}
function _tsv(){var e=document.getElementById('settingSecret');e.type=e.type==='password'?'text':'password'}
window.addEventListener('DOMContentLoaded',()=>{var s=localStorage.getItem('angel_creator_secret');if(s)document.getElementById('settingSecret').value=s;});
async function _cp(){var o=document.getElementById('oldPassword').value,n=document.getElementById('newPassword').value,c=document.getElementById('confirmPassword').value;if(!o||!n){_t('\u586b\u586b\u586b','error');return;}if(n!==c){_t('\u4e24\u6b21\u5bc6\u4e0d\u4e00\u4e00','error');return;}if(n.length<6){_t('\u5bc6\u7801\u81f36\u81f46','error');return;}try{var sb=await _gS();var{err}=await sb.rpc('change_admin_password',{p_username:_ca.username,p_old_password:o,p_new_password:n});if(err) throw err;_t('\u2705 \u5bc6\u4fee\u6539\u6210\u6210!','success');document.getElementById('oldPassword').value='';document.getElementById('newPassword').value='';document.getElementById('confirmPassword').value='';}catch(e){_t(`\u4fee\u5931\u5931:${e.message}`,'error')}}
/* 兼容别名 */
var loadStats=_lSts,loadPendingRequests=_lPr,switchAdminTab=_sat,saveSettings=_ss,toggleSecretVisibility=_tsv,changePassword=_cp,showRejectModal=_sr,closeRejectModal=_cr,approveRequest=_ap,filterAllRequests=_fA;
